server:
  port: 0

# id приложения eureka
spring:
  application:
    name: eclient

# url, куда будет происходить регистрация микросервисов
eureka:
  client:
    enabled: true # вместо @EnableEurekaClient
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
  instance:
    instance-id: ${spring.application.name}:${random.uuid} # для уникального экземпляра приложения

# формат логов
logging:
  pattern:
    console: "%C{1.} [%-5level] %d{HH:mm:ss} - %msg%n"
